---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    keypair: my-key325
    region: us-east-1
    image: ami-09d56f8956ab235b3 # https://cloud-images.ubuntu.com/locator/ec2/
    id: "web-app"
    sec_group: "{{ id }}-sec"

  tasks:

    # - name: Get instances facts
    #   ec2_instance_facts:
    #     aws_access_key: "{{ec2_access_key}}"
    #     aws_secret_key: "{{ec2_secret_key}}"
    #     region: "{{ region }}"
    #   register: result

    # - name: Instances ID
    #   debug:
    #     msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
    #   loop: "{{ result.instances }}"



    - name: Provision instance(s)
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        key_name: "{{ keypair }}"
        group: MySecurityGroup325  # security group name
        id: "{{ id }}"
        image: "{{ image }}"
        instance_type: t2.micro
        region: "{{ region }}"
        wait: true
        count: 1
    # tags: ['never', 'create_ec2']